### ISSUE TITLE
Does swizzling need to add selectors?

### ISSUE THREAD

**Issue by grp** [ebf/CTObjectiveCRuntimeAdditions#2]
I'm not sure why this library needs to add selectors to the class to do swizzling. Although that is the common method, it can have issues if the same method is swizzled more than once. Instead, why not simply return the current implementation `from class_swizzleSelectorWithBlock()`, and then capture that in the block?

For example:

```
__block IMP originalImplementation = class_swizzleSelectorWithBlock([CTTestSwizzleClass class], @selector(helloWorldStringFromString:), ^NSString *(CTTestSwizzleClass *blockSelf, NSString *string) {
    return [originalImplementation(blockSelf, @selector(helloWorldStringFromString:), string) stringByAppendingFormat:@" Hooked"];
});
```

That would also simplify the implementation and allow the block to simply be called without any parameter shuffling.

Maybe I'm missing something that would make this impractical or not useful?

**Comment by OliverLetterer** [comment]
I think you might have a point here. By the time of writing `class_swizzleSelectorWithBlock` i started reading about trampolines and got kind of excited about them. So I was looking for a possible scenario where I could play with a trampoline. Passing the original implementation at runtime to the block as a parameter seemed as a good and cool way for me. Now I only had one weekend for this as a hobby project and as it turned out, this was not enough time for me to write a custom low level trampoline. Therefore libffi was included...
- One minor downside of not storing the previous implementation might be, that it can't be swizzled back very easily.
- `class_swizzleSelectorWithBlock` would be the wrong naming then. `class_replaceMethodWithBlock` might be better.
